version: '3.4'
services: 
  telco-sandbox:
    build: 
      context: ../../
      dockerfile: ./misc/docker/dockerfile
    restart: unless-stopped
    environment: 
      - NODE_ENV=production
  telco-sandbox-proxy:
    environment:
      CADDY_CONF: |
        :80 {
          proxy / admin-portal:3000
        }
        :443 {
          tls self_signed
          proxy / telco-sandbox-react:3000
          proxy /socket.io telco-sandbox:80
        }
    entrypoint: /bin/sh
    command: -c 'echo "$$CADDY_CONF" | caddy -conf stdin'
    networks:
      default:
        aliases:
          - telco-sandbox.internal
  